#ifndef PCC_DOCA_COMPAT_H_
#define PCC_DOCA_COMPAT_H_

#include <doca_version.h>

#define DOCA_VERSION_AT_LEAST(major, minor) \
	((DOCA_VERSION_MAJOR > (major)) || \
	 (DOCA_VERSION_MAJOR == (major) && DOCA_VERSION_MINOR >= (minor)))

#define DOCA_HAS_PCC_DEBUG_API DOCA_VERSION_AT_LEAST(2, 8)
#define DOCA_HAS_DEVICE_REPRESENTORS (DOCA_VERSION_MAJOR >= 3)
#define DOCA_HAS_PCC_TRACE_REPORTS (DOCA_VERSION_MAJOR >= 3)
#define DOCA_HAS_TIMESTAMPED_PCC_TRACE_LAYOUT DOCA_VERSION_AT_LEAST(3, 4)
#define DOCA_HAS_NATIVE_FLOW_HASH (DOCA_VERSION_MAJOR >= 3)
#define DOCA_USES_LEGACY_FLOW_BACKEND (DOCA_VERSION_MAJOR < 3)
#define DOCA_HAS_FLOW_SHARED_RESOURCE_SET_CFG DOCA_VERSION_AT_LEAST(2, 8)
#define DOCA_HAS_MIRROR_ORIGINAL_FWD \
	(DOCA_VERSION_MAJOR < 3 && DOCA_VERSION_MINOR < 9)
#define DOCA_USES_LEGACY_PIPE_RM_API \
	(DOCA_VERSION_MAJOR < 3 && DOCA_VERSION_MINOR < 9)
#define DOCA_HAS_PORT_FLOW_RESOURCES DOCA_VERSION_AT_LEAST(3, 2)
#define DOCA_HAS_EXPLICIT_FLOW_ACTION_INDEX DOCA_VERSION_AT_LEAST(3, 4)
#define DOCA_HAS_DPA_RESOURCES_FILE DOCA_VERSION_AT_LEAST(3, 4)

#endif /* PCC_DOCA_COMPAT_H_ */
